### ISSUE TITLE
[Question]: <Add a new tag "oceanbase".>

### ISSUE THREAD

**Issue by eudoratian** [oceanbase/obkv-hbase-client-java#6]
I am a member of the Oceanbase organization. Your project is great. Would it be possible to add the Oceanbase tag?

**Comment by IHEII** [comment]
@hnwyllmm Hi mate, could you help to add this tag

**Comment by hnwyllmm** [comment]
I don't understand you.
Do you mean add a label "oceanbase" on the main page?
